apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: fastapi-container
          image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${GIT_TAG}
          ports:
            - containerPort: 80

